### ISSUE TITLE
Portal 2 `base.fgd` only loads the first 6 `@BaseClass`

### ISSUE THREAD

**Issue by snake-biscuits** [maxdup/fgd-tools#5]
Opening this issue here because `ValveFGD` doesn't have Issues enabled (Settings>General>Issues in GitHub to resolve)

[VDC copy of `Portal 2/bin/base.fgd`](https://developer.valvesoftware.com/wiki/Base.fgd/Portal_2)
can only load the fgd up to Line 67:
`@BaseClass base(Reflection, ToggleDraw, Shadow) = Studiomodel`
all ~300 entities after this point are absent.

**Comment by maxdup** [comment]
wrong repo sorry 🙃 https://github.com/pySourceSDK/ValveFGD

But I was able to reproduce the error with ValveFGD. Will look into it and submit an update

**Comment by snake-biscuits** [comment]
> wrong repo sorry 🙃 [pySourceSDK/ValveFGD](https://github.com/pySourceSDK/ValveFGD)

I actually couldn't open an Issue on ValveFGD
https://github.com/pySourceSDK/ValveFGD/issues redirects to the pull requests tab
My guess is issues aren't enabled on the fork (which appears to be GitHub's default behaviour)
Which is what I meant by this line:

> Opening this issue here because ValveFGD doesn't have Issues enabled (Settings>General>Issues in GitHub to resolve)

**Comment by maxdup** [comment]
Thanks for pointing that out, I've opened issues on ValveFGD.

I've fixed the issue and updated ValveFGD to v1.0.3
It's currently live on pypi https://pypi.org/project/valvefgd/#history
